### ISSUE TITLE
How disable line wrap in front matter (for Hugo or Jekyll)

### ISSUE THREAD

**Issue by apoutchika** [preservim/vim-pencil#92]
Hi,

When use front matter in markdown file :

```markdown
---
Author: Test
Description: Test
---

# Test
```

If i try to update or add parameters in front matter, Pencil remove all new line : 

Try to add Title Between Autor and Description :
```markdown
--- Author: Test Title Description: Test ---

# Test
```
How to disable this only for this part ?

**Comment by antgel** [comment]
Thanks for opening this. I too would love to know. Currently I'm manually disabling Pencil, and it's quite annoying.

**Comment by alerque** [comment]
I don't think VIM supports region based wrap settings at all. If anybody knows of any language or plugin that supports this please mention it here and we can look into how they did it, but off the top of y head this may not be possible.

**Comment by reedes** [comment]
I've recently started using Jekyll and see that it's using "yaml" prefixed highlight groups in the markdown headers.

These highlight groups can be identified (from the syntax files) and added to the pencil blacklist, to ensure that autoformat won't be enabled if entering insert mode in hard line break mode.

If I get a chance, I'll dig into this further.

**Comment by antgel** [comment]
@reedes Looking forward to hearing what you find; I just found this issue and I didn't know what I had been doing wrong! By the way, why is Pencil doing this at all? What's the intention? Is it that it thinks the lines should be wrapped into one paragraph because there is no blank line between them?

**Comment by reedes** [comment]
A minor error in my regex. I'll look at getting it fixed in the next few days and will generate a fresh pull request.

(The recent merged request shouldn't break anything, so no need to revert it.)

**Comment by antgel** [comment]
@reedes Thanks so much for this, amazing how such a small code change can have such a big impact!
